
-- CREATE DATABASE DNGOAI_KHOA
CREATE DATABASE DNGOAI_KHOA;


-- SELECT DATABASE DNGOAI_KHOA
USE DNGOAI_KHOA;

-- TẠO BẢNG QUYỀN NHÂN VIÊN
CREATE TABLE TQUYEN_NHAN_VIEN( 
    FMA_QUYEN_NHAN_VIEN CHARACTER(30) NOT NULL PRIMARY KEY, 
    FTEN_QUYEN_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL
) ENGINE = InnoDB;

-- TẠO BẢNG NHÂN VIÊN
CREATE TABLE TNHAN_VIEN( 
    FMA_NHAN_VIEN INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    FHO_TEN_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL , 
    FTAI_KHOAN_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL , 
    FMAT_KHAU_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT '12345' NOT NULL , 
    FMA_QUYEN_NHAN_VIEN CHARACTER(30) NOT NULL,
    FOREIGN KEY (FMA_QUYEN_NHAN_VIEN) REFERENCES TQUYEN_NHAN_VIEN(FMA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB;


-- TẠO BẢNG VAI TRÒ CỦA QUYỀN
CREATE TABLE TTINH_NANG(
    FMA_QUYEN_NHAN_VIEN CHARACTER(30) NOT NULL UNIQUE,
    FMA_TINH_NANG CHARACTER(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL, 
    FTEN_TINH_NANG CHARACTER(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL,
    FDUOC_TRUY_CAP CHARACTER(3) NOT NULL DEFAULT 'YES',
    FOREIGN KEY (FMA_QUYEN_NHAN_VIEN )REFERENCES TQUYEN_NHAN_VIEN(FMA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB;


-- THÊM DỮ LIỆU VÀO BẢNG QUYỀN NHÂN_VIEN
INSERT INTO TQUYEN_NHAN_VIEN(
    FMA_QUYEN_NHAN_VIEN, 
    FTEN_QUYEN_NHAN_VIEN
) 
VALUES 
    ('NGUOI_QUAN_TRI_HE_THONG', 'NGUOI_QUAN_TRI_HE_THONG'),
    ('PHAU_THUAT_VIEN', 'PHẨU THUẬT VIÊN');



-- THÊM DỮ LIỆU BẢNG NHÂN VIÊN
INSERT INTO TNHAN_VIEN(
    FHO_TEN_NHAN_VIEN,
    FTAI_KHOAN_NHAN_VIEN,
    FMA_QUYEN_NHAN_VIEN
) 
VALUES ('HUỲNH THANH LỘC', 'LOCHT', 'NGUOI_QUAN_TRI_HE_THONG'),
       ('NGUYỄN THANH HIỀN', 'HIENNT', 'PHAU_THUAT_VIEN');


-- THÊM DỮ LIỆU BẢNG TTINH_NANG
INSERT INTO TTINH_NANG(
    FMA_QUYEN_NHAN_VIEN,
    FMA_TINH_NANG,
    FTEN_TINH_NANG,
    FDUOC_TRUY_CAP
) VALUES 
    ('NGUOI_QUAN_TRI_HE_THONG', 'LICH_HEN_MO_PHONG_KHAM_NGOAI', 'LỊCH HẸN MỔ PHÒNG KHÁM', 'YES'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'HO_CHAN_DUYET_MO', 'HỘ CHẨN DUYỆT MỔ', 'YES'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'LICH_MO_TAM', 'LỊCH MỔ TẠM', 'YES'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'LICH_HEN_MO_PHONG_KHAM_NGOAI', 'LỊCH HẸN MỔ PHÒNG KHÁM', 'YES'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'LICH_HEN_MO_PHONG_KHAM_NGOAI', 'LỊCH HẸN MỔ PHÒNG KHÁM', 'YES'),;