
-- CREATE DATABASE DNGOAI_KHOA
CREATE DATABASE DNGOAI_KHOA;


-- SELECT DATABASE DNGOAI_KHOA
USE DNGOAI_KHOA;

-- TẠO BẢNG QUYỀN NHÂN VIÊN
CREATE TABLE TQUYEN_NHAN_VIEN( 
    FMA_QUYEN_NHAN_VIEN CHARACTER(30) NOT NULL PRIMARY KEY, 
    FTEN_QUYEN_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL
) ENGINE = InnoDB;

-- TẠO BẢNG NHÂN VIÊN
CREATE TABLE TNHAN_VIEN( 
    FMA_NHAN_VIEN INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    FHO_TEN_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL , 
    FTAI_KHOAN_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL , 
    FMAT_KHAU_NHAN_VIEN VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT '12345' NOT NULL , 
    FMA_QUYEN_NHAN_VIEN CHARACTER(30) NOT NULL,
    FOREIGN KEY (FMA_QUYEN_NHAN_VIEN) REFERENCES TQUYEN_NHAN_VIEN(FMA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB;


-- TẠO BẢNG VAI TRÒ CỦA QUYỀN
CREATE TABLE TTINH_NANG(
    FMA_QUYEN_NHAN_VIEN CHARACTER(30) NOT NULL,
    FMA_TINH_NANG CHARACTER(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL, 
    FTEN_TINH_NANG CHARACTER(30) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL,
    FDUOC_PHEP_TAO ENUM('TRUE','FALSE') DEFAULT 'TRUE' NOT NULL ,
    FDUOC_PHEP_SUA ENUM('TRUE','FALSE') DEFAULT 'TRUE' NOT NULL ,
    FDUOC_PHEP_XOA ENUM('TRUE','FALSE') DEFAULT 'TRUE' NOT NULL ,
    FDUOC_PHEP_XEM ENUM('TRUE','FALSE') DEFAULT 'TRUE' NOT NULL ,
    FCODE VARCHAR(50) CHARACTER SET UTF8 NOT NULL ,
    FOREIGN KEY (FMA_QUYEN_NHAN_VIEN )REFERENCES TQUYEN_NHAN_VIEN(FMA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB;

CREATE TABLE TBENH_NHAN(
    FMA_BENH_NHAN INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FHO_TEN_BENH_NHAN CHARACTER(30) NOT NULL, 
    FGIOI_TINH ENUM('Nam','Nữ') DEFAULT 'Nam' NOT NULL ,
    FNAM_SINH YEAR(4) NOT NULL,
    FDIA_CHI VARCHAR(30) DEFAULT '',
    FXA_PHUONG VARCHAR(30) DEFAULT '',
    FQUAN_HUYEN VARCHAR(30) DEFAULT '',
    FTINH_THANH VARCHAR(30) NOT NULL,
    FCHAN_DOAN VARCHAR(30) NOT NULL DEFAULT '',
    FNGUOI_HEN INT(3) NOT NULL,
    FNGAY_HEN DATE NOT NULL,
    FGHI_CHU TEXT,
    FOREIGN KEY (FNGUOI_HEN) REFERENCES TNHAN_VIEN(FMA_NHAN_VIEN)
) ENGINE = INNODB,CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

-- THÊM DỮ LIỆU VÀO BẢNG QUYỀN NHÂN_VIEN
INSERT INTO TQUYEN_NHAN_VIEN(
    FMA_QUYEN_NHAN_VIEN, 
    FTEN_QUYEN_NHAN_VIEN
) 
VALUES 
    ('NGUOI_QUAN_TRI_HE_THONG', 'NGƯỜI QUẢN TRỊ HỆ THỐNG'),
    ('PHAU_THUAT_VIEN', 'PHẨU THUẬT VIÊN');



-- THÊM DỮ LIỆU BẢNG NHÂN VIÊN
INSERT INTO TNHAN_VIEN(
    FHO_TEN_NHAN_VIEN,
    FTAI_KHOAN_NHAN_VIEN,
    FMA_QUYEN_NHAN_VIEN
) 
VALUES ('HUỲNH THANH LỘC', 'LOCHT', 'NGUOI_QUAN_TRI_HE_THONG'),
       ('NGUYỄN THANH HIỀN', 'HIENNT', 'PHAU_THUAT_VIEN');


-- THÊM DỮ LIỆU BẢNG TTINH_NANG
INSERT INTO TTINH_NANG(
    FMA_QUYEN_NHAN_VIEN,
    FMA_TINH_NANG,
    FTEN_TINH_NANG,
    FDUOC_PHEP_TAO,
    FDUOC_PHEP_SUA,
    FDUOC_PHEP_XOA,
    FCODE
) VALUES 
    ('NGUOI_QUAN_TRI_HE_THONG', 'LICH_MO', 'LỊCH MỔ', 'TRUE', 'TRUE', 'TRUE' , './php_mvc/lich_mo/xem_lich_mo'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'LICH_HEN', 'LỊCH HẸN', 'TRUE', 'TRUE', 'TRUE' , './php_mvc/lich_hen/xem_lich_hen'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'DUYET_MO', 'DUYỆT MỔ', 'TRUE', 'TRUE', 'TRUE' , './php_mvc/duyet_mo/xem_duyet_mo'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'TIEN_ME', 'TIỀN MÊ', 'TRUE', 'TRUE', 'TRUE' , './php_mvc/tien_me/xem_tien_me'),
    ('NGUOI_QUAN_TRI_HE_THONG', 'NHAN_VIEN', 'NHÂN VIÊN', 'TRUE', 'TRUE', 'TRUE' , './php_mvc/nhan_vien/xem_nhan_vien');