SET GLOBAL TIME_ZONE = "7:00";

CREATE DATABASE IF NOT EXISTS NGOAI_KHOA DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE IF NOT EXISTS NGOAI_KHOA;

CREATE TABLE IF NOT EXISTS QUYEN_NHAN_VIEN(
    MA_QUYEN_NHAN_VIEN     VARCHAR(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEN_QUYEN_NHAN_VIEN    VARCHAR(50)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 

CREATE TABLE IF NOT EXISTS NHAN_VIEN(
    MA_NHAN_VIEN INT(2) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HO_TEN_NHAN_VIEN VARCHAR(30) NOT NULL,
    EMAIL_NHAN_VIEN VARCHAR(30) NOT NULL,
    TAI_KHOAN_NHAN_VIEN VARCHAR(30) NOT NULL,
    MAT_KHAU_NHAN_VIEN LONGTEXT NOT NULL,
    MA_QUYEN_NHAN_VIEN VARCHAR(30) NOT NULL,
    UNIQUE(HO_TEN_NHAN_VIEN, EMAIL_NHAN_VIEN, TAI_KHOAN_NHAN_VIEN),
    FOREIGN KEY(MA_QUYEN_NHAN_VIEN) REFERENCES QUYEN_NHAN_VIEN(MA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 

CREATE TABLE IF NOT EXISTS CHUC_NANG_CUA_QUYEN(
    MA_QUYEN_NHAN_VIEN  VARCHAR(30) NOT NULL,
    MA_CHUC_NANG        VARCHAR(30) NOT NULL,
    TEN_CHUC_NANG       VARCHAR(50),
    XEM_TRANG           ENUM('TRUE', 'FALSE') NOT NULL,
    THEM_TRANG          ENUM('TRUE', 'FALSE') NOT NULL,
    SUA_TRANG           ENUM('TRUE', 'FALSE') NOT NULL,
    XOA_TRANG           ENUM('TRUE', 'FALSE') NOT NULL,
    LINK_TRANG          VARCHAR(50) NOT NULL,
    FOREIGN KEY(MA_QUYEN_NHAN_VIEN) REFERENCES QUYEN_NHAN_VIEN(MA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 

