SET GLOBAL TIME_ZONE = "+7:00";

CREATE DATABASE IF NOT EXISTS KHOA_NGOAI DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE KHOA_NGOAI;

CREATE TABLE IF NOT EXISTS QUYEN_NHAN_VIEN(
    MA_QUYEN_NHAN_VIEN     VARCHAR(30) NOT NULL PRIMARY KEY,
    TEN_QUYEN_NHAN_VIEN    VARCHAR(50)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 

CREATE TABLE IF NOT EXISTS NHIEM_VU_NHAN_VIEN(
    ID INT(3) NOT NULl AUTO_INCREMENT PRIMARY KEY,
    MA_QUYEN_NHAN_VIEN      VARCHAR(30) NOT NULL,
    MA_NHIEM_VU_NHAN_VIEN   VARCHAR(30) NOT NULL,
    TEN_NHIEM_VU_NHAN_VIEN  VARCHAR(50) NOT NULL,
    DUOC_PHEP_XEM           ENUM('TRUE','FALSE') DEFAULT 'TRUE',
    DUOC_PHEP_THEM          ENUM('TRUE','FALSE') DEFAULT 'TRUE',
    DUOC_PHEP_SUA           ENUM('TRUE','FALSE') DEFAULT 'TRUE',
    DUOC_PHEP_XOA           ENUM('TRUE','FALSE') DEFAULT 'TRUE',
    DUOC_PHEP_MO_MODAL_SUA  ENUM('TRUE','FALSE') DEFAULT 'TRUE',
    DUOC_PHEP_MO_MODAL_XOA  ENUM('TRUE','FALSE') DEFAULT 'TRUE',
    HREF LONGTEXT DEFAULT 'index.php?controller=&method=',
    FOREIGN KEY(MA_QUYEN_NHAN_VIEN) REFERENCES QUYEN_NHAN_VIEN(MA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 

CREATE TABLE IF NOT EXISTS NHAN_VIEN(
    MA_NHAN_VIEN INT(2) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HO_TEN_NHAN_VIEN VARCHAR(30) NOT NULL,
    EMAIL_NHAN_VIEN VARCHAR(30) NOT NULL,
    TAI_KHOAN_NHAN_VIEN VARCHAR(30) NOT NULL,
    MAT_KHAU_NHAN_VIEN LONGTEXT NOT NULL,
    MA_QUYEN_NHAN_VIEN VARCHAR(30) NOT NULL,
    UNIQUE(HO_TEN_NHAN_VIEN, EMAIL_NHAN_VIEN, TAI_KHOAN_NHAN_VIEN),
    FOREIGN KEY(MA_QUYEN_NHAN_VIEN) REFERENCES QUYEN_NHAN_VIEN(MA_QUYEN_NHAN_VIEN)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 



INSERT INTO `quyen_nhan_vien` (`MA_QUYEN_NHAN_VIEN`, `TEN_QUYEN_NHAN_VIEN`) VALUES ('ADMIN', 'Quản Trị Viên'), ('PHAU_THUAT_VIEN', 'Phẩu Thuật Viên');
INSERT INTO `nhiem_vu_nhan_vien` (`ID`, `MA_QUYEN_NHAN_VIEN`, `MA_NHIEM_VU_NHAN_VIEN`, `TEN_NHIEM_VU_NHAN_VIEN`, `DUOC_PHEP_XEM`, `DUOC_PHEP_THEM`, `DUOC_PHEP_SUA`, `DUOC_PHEP_XOA`, `DUOC_PHEP_MO_MODAL_SUA`, `DUOC_PHEP_MO_MODAL_XOA`, `HREF`) VALUES (NULL, 'ADMIN', 'NHAN_VIEN', 'Nhân Viên', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'index.php?controller=nhan_vien&method=nhan_vien');
INSERT INTO `nhan_vien` (`MA_NHAN_VIEN`, `HO_TEN_NHAN_VIEN`, `EMAIL_NHAN_VIEN`, `TAI_KHOAN_NHAN_VIEN`, `MAT_KHAU_NHAN_VIEN`, `MA_QUYEN_NHAN_VIEN`) VALUES (NULL, 'Huỳnh Thanh Lộc', 'schooling010@gmail.com', 'LOCHT', '827ccb0eea8a706c4c34a16891f84e7b', 'ADMIN');

DELIMITER $$
CREATE PROCEDURE  CHECK_LOGIN(IN TAI_KHOAN VARCHAR(30) CHARACTER SET UTF8, IN MAT_KHAU LONGTEXT)
BEGIN 
    SELECT NHAN_VIEN.MA_NHAN_VIEN, 
           NHAN_VIEN.HO_TEN_NHAN_VIEN, 
           NHAN_VIEN.EMAIL_NHAN_VIEN, 
           NHAN_VIEN.TAI_KHOAN_NHAN_VIEN, 
           NHAN_VIEN.MA_QUYEN_NHAN_VIEN,
           QUYEN_NHAN_VIEN.TEN_QUYEN_NHAN_VIEN
    FROM NHAN_VIEN INNER JOIN QUYEN_NHAN_VIEN ON NHAN_VIEN. MA_QUYEN_NHAN_VIEN = QUYEN_NHAN_VIEN.MA_QUYEN_NHAN_VIEN
    WHERE NHAN_VIEN.TAI_KHOAN_NHAN_VIEN = TAI_KHOAN AND NHAN_VIEN.MAT_KHAU_NHAN_VIEN = MD5(MAT_KHAU);
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE  GET_PERMISSIONS(IN ROLE_ID VARCHAR(30) CHARACTER SET UTF8)
BEGIN 
    SELECT  MA_NHIEM_VU_NHAN_VIEN ,
            TEN_NHIEM_VU_NHAN_VIEN,
            DUOC_PHEP_XEM,
            DUOC_PHEP_THEM,        
            DUOC_PHEP_SUA,         
            DUOC_PHEP_XOA,         
            DUOC_PHEP_MO_MODAL_SUA,
            DUOC_PHEP_MO_MODAL_XOA,
            HREF
    FROM NHIEM_VU_NHAN_VIEN 
    WHERE MA_QUYEN_NHAN_VIEN = ROLE_ID;
END $$
DELIMITER ;
